name: Build and Release Qt6 Project

on:
  push:
    branches:
      - master
      - ci
  release:
    types: [created]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-2019, macos-latest]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Qt
      uses: jurplel/install-qt-action@v4
      with:
        version: '6.7.2'
        target: 'desktop'
        dir:  ${{ runner.temp }}
    - name: Set up Visual Studio shell
      if: matrix.os == 'windows-2019'
      uses: egor-tensin/vs-shell@v2
      with:
          arch: x64

    - name: Create build directory
      run:  mkdir ${{ runner.temp }}\build

    - name: Build Project
      run: |
        mkdir build
        cd build
        qmake ../analogclock/analogclock.pro
        make -j$(nproc) || nproc
        ls -l
      shell: bash

    - name: Archive binary
      if: matrix.os == 'ubuntu-latest'
      run: zip -j analogclock-linux.zip build/analogclock
      shell: bash

    - name: Archive binary
      if: matrix.os == 'windows-latest'
      run: 7z a analogclock-windows.zip build\analogclock.exe
      shell: cmd

    - name: Archive binary
      if: matrix.os == 'macos-latest'
      run: zip -j analogclock-macos.zip build/analogclock
      shell: bash

    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: ${{ matrix.os }}-analogclock
        path: |
          analogclock-linux.zip
          analogclock-windows.zip
          analogclock-macos.zip

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Download Artifacts
      uses: actions/download-artifact@v3
      with:
        path: ./artifacts

    - name: Create Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: |
          ./artifacts/analogclock-linux.zip
          ./artifacts/analogclock-windows.zip
          ./artifacts/analogclock-macos.zip
        token: ${{ secrets.GITHUB_TOKEN }}
        tag: ${{ github.ref_name }}
        name: Release ${{ github.ref_name }}
        body: |
          Binaries for Linux, Windows, and macOS are included.
        draft: false
        prerelease: false
